#############################################################################
# Makefile for building: bin/PicturePro
# Generated by qmake (3.1) (Qt 5.15.10)
# Project:  PicturePro.pro
# Template: app
# Command: /home/zhao/study_apps/qt5.15_arm/Qt_arm/bin/qmake -o Makefile PicturePro.pro -spec linux-arm-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = arm-buildroot-linux-gnueabihf-gcc
CXX           = arm-buildroot-linux-gnueabihf-g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -pipe -g -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -std=c++14 -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -pipe -g -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /home/zhao/study_apps/qt5.15_arm/Qt_arm/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/zhao/study_apps/qt5.15_arm/Qt_arm/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/zhao/study_apps/qt5.15_arm/Qt_arm/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PicturePro1.0.0
DISTDIR = /home/zhao/qrs_study/imx6ull_pro/PicturePro/tmp_release/PicturePro1.0.0
LINK          = arm-buildroot-linux-gnueabihf-g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lfreetype -lm -lpthread -lts -ljpeg   
AR            = arm-buildroot-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-buildroot-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = tmp_release/

####### Files

SOURCES       = debug/debug_manager.c \
		debug/netprint.c \
		debug/stdout.c \
		display/disp_manager.c \
		display/fb.c \
		encoding/ascii.c \
		encoding/encoding_manager.c \
		encoding/utf-16be.c \
		encoding/utf-16le.c \
		encoding/utf-8.c \
		file/file.c \
		fonts/ascii_font.c \
		fonts/fonts_manager.c \
		fonts/freetype.c \
		fonts/gbk.c \
		input/input_manager.c \
		input/stdin.c \
		input/touchscreen.c \
		libjpeg/libjpeg.c \
		main.c \
		page/auto_page.c \
		page/browse_page.c \
		page/interval_page.c \
		page/main_page.c \
		page/manual_page.c \
		page/page_manager.c \
		page/setting_page.c \
		render/format/bmp.c \
		render/format/jpg.c \
		render/format/picfmt_manager.c \
		render/operation/merge.c \
		render/operation/zoom.c \
		render/render.c 
OBJECTS       = tmp_release/debug_manager.o \
		tmp_release/netprint.o \
		tmp_release/stdout.o \
		tmp_release/disp_manager.o \
		tmp_release/fb.o \
		tmp_release/ascii.o \
		tmp_release/encoding_manager.o \
		tmp_release/utf-16be.o \
		tmp_release/utf-16le.o \
		tmp_release/utf-8.o \
		tmp_release/file.o \
		tmp_release/ascii_font.o \
		tmp_release/fonts_manager.o \
		tmp_release/freetype.o \
		tmp_release/gbk.o \
		tmp_release/input_manager.o \
		tmp_release/stdin.o \
		tmp_release/touchscreen.o \
		tmp_release/libjpeg.o \
		tmp_release/main.o \
		tmp_release/auto_page.o \
		tmp_release/browse_page.o \
		tmp_release/interval_page.o \
		tmp_release/main_page.o \
		tmp_release/manual_page.o \
		tmp_release/page_manager.o \
		tmp_release/setting_page.o \
		tmp_release/bmp.o \
		tmp_release/jpg.o \
		tmp_release/picfmt_manager.o \
		tmp_release/merge.o \
		tmp_release/zoom.o \
		tmp_release/render.o
DIST          = icon/browse_mode.bmp \
		icon/cancel.bmp \
		icon/continue_mod.bmp \
		icon/continue_mod_small.bmp \
		icon/file.bmp \
		icon/fold_closed.bmp \
		icon/fold_opened.bmp \
		icon/interval.bmp \
		icon/next_page.bmp \
		icon/next_pic.bmp \
		icon/ok.bmp \
		icon/pre_page.bmp \
		icon/pre_pic.bmp \
		icon/return.bmp \
		icon/select.bmp \
		icon/select_fold.bmp \
		icon/setting.bmp \
		icon/time.bmp \
		icon/up.bmp \
		icon/zoomin.bmp \
		icon/zoomout.bmp \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/spec_pre.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/unix.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/linux.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/sanitize.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/gcc-base.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/gcc-base-unix.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/g++-base.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/g++-unix.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/qconfig.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_charts.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_charts_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_concurrent.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_core.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_core_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_dbus.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gamepad.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gui.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gui_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_help.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_help_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimedia.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_network.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_network_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_networkauth.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_nfc.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_positioning.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_printsupport.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_purchasing.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_repparser.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_script.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_script_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_scripttools.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sensors.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialbus.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialport.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sql.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sql_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_svg.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_svg_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_testlib.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uitools.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_webchannel.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_websockets.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_widgets.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xml.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xml_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qt_functions.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qt_config.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/exclusive_builds.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/toolchain.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/default_pre.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/resolve_config.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/default_post.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qml_debug.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/warn_on.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qmake_use.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/file_copies.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/testcase_targets.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/exceptions.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/yacc.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/lex.prf \
		PicturePro.pro include/config.h \
		include/debug_manager.h \
		include/disp_manager.h \
		include/draw.h \
		include/encoding_manager.h \
		include/file.h \
		include/fonts_manager.h \
		include/input_manager.h \
		include/page_manager.h \
		include/pic_operation.h \
		include/picfmt_manager.h \
		include/render.h debug/debug_manager.c \
		debug/netprint.c \
		debug/stdout.c \
		display/disp_manager.c \
		display/fb.c \
		encoding/ascii.c \
		encoding/encoding_manager.c \
		encoding/utf-16be.c \
		encoding/utf-16le.c \
		encoding/utf-8.c \
		file/file.c \
		fonts/ascii_font.c \
		fonts/fonts_manager.c \
		fonts/freetype.c \
		fonts/gbk.c \
		input/input_manager.c \
		input/stdin.c \
		input/touchscreen.c \
		libjpeg/libjpeg.c \
		main.c \
		page/auto_page.c \
		page/browse_page.c \
		page/interval_page.c \
		page/main_page.c \
		page/manual_page.c \
		page/page_manager.c \
		page/setting_page.c \
		render/format/bmp.c \
		render/format/jpg.c \
		render/format/picfmt_manager.c \
		render/operation/merge.c \
		render/operation/zoom.c \
		render/render.c
QMAKE_TARGET  = PicturePro
DESTDIR       = bin/
TARGET        = bin/PicturePro


first: all
####### Build rules

bin/PicturePro:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PicturePro.pro ../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf ../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/spec_pre.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/unix.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/linux.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/sanitize.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/gcc-base.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/gcc-base-unix.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/g++-base.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/g++-unix.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/qconfig.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_charts.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_charts_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_concurrent.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_core.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_core_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_dbus.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gamepad.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gui.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gui_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_help.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_help_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimedia.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_network.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_network_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_networkauth.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_nfc.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_positioning.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_printsupport.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_purchasing.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_repparser.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_script.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_script_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_scripttools.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sensors.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialbus.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialport.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sql.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sql_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_svg.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_svg_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_testlib.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uitools.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_webchannel.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_websockets.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_widgets.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xml.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xml_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qt_functions.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qt_config.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/exclusive_builds.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/toolchain.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/default_pre.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/resolve_config.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/default_post.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qml_debug.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/warn_on.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qmake_use.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/file_copies.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/testcase_targets.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/exceptions.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/yacc.prf \
		../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/lex.prf \
		PicturePro.pro
	$(QMAKE) -o Makefile PicturePro.pro -spec linux-arm-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/spec_pre.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/unix.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/linux.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/sanitize.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/gcc-base.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/gcc-base-unix.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/g++-base.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/common/g++-unix.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/qconfig.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bluetooth.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_charts.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_charts_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_concurrent.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_core.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_core_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_dbus.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_dbus_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gamepad.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gui.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_gui_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_help.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_help_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_input_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimedia.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_network.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_network_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_networkauth.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_nfc.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_nfc_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_positioning.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_positioning_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_printsupport.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_purchasing.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_repparser.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_repparser_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_script.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_script_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_scripttools.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sensors.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sensors_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialbus.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialport.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_serialport_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_service_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sql.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_sql_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_svg.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_svg_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_testlib.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_testlib_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_texttospeech.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uiplugin.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uitools.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_uitools_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandclient.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_webchannel.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_websockets.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_websockets_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_widgets.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_widgets_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xml.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xml_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/modules/qt_lib_zlib_private.pri:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qt_functions.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qt_config.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/exclusive_builds.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/toolchain.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/default_pre.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/resolve_config.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/default_post.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qml_debug.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/warn_on.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/qmake_use.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/file_copies.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/testcase_targets.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/exceptions.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/yacc.prf:
../../../study_apps/qt5.15_arm/Qt_arm/mkspecs/features/lex.prf:
PicturePro.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile PicturePro.pro -spec linux-arm-gnueabi-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile bin/PicturePro

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

tmp_release/debug_manager.o: debug/debug_manager.c include/config.h \
		include/debug_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/debug_manager.o debug/debug_manager.c

tmp_release/netprint.o: debug/netprint.c include/config.h \
		include/debug_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/netprint.o debug/netprint.c

tmp_release/stdout.o: debug/stdout.c include/config.h \
		include/debug_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/stdout.o debug/stdout.c

tmp_release/disp_manager.o: display/disp_manager.c include/config.h \
		include/debug_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/disp_manager.o display/disp_manager.c

tmp_release/fb.o: display/fb.c include/config.h \
		include/debug_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/fb.o display/fb.c

tmp_release/ascii.o: encoding/ascii.c include/config.h \
		include/debug_manager.h \
		include/encoding_manager.h \
		include/fonts_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/ascii.o encoding/ascii.c

tmp_release/encoding_manager.o: encoding/encoding_manager.c include/config.h \
		include/debug_manager.h \
		include/encoding_manager.h \
		include/fonts_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/encoding_manager.o encoding/encoding_manager.c

tmp_release/utf-16be.o: encoding/utf-16be.c include/config.h \
		include/debug_manager.h \
		include/encoding_manager.h \
		include/fonts_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/utf-16be.o encoding/utf-16be.c

tmp_release/utf-16le.o: encoding/utf-16le.c include/config.h \
		include/debug_manager.h \
		include/encoding_manager.h \
		include/fonts_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/utf-16le.o encoding/utf-16le.c

tmp_release/utf-8.o: encoding/utf-8.c include/config.h \
		include/debug_manager.h \
		include/encoding_manager.h \
		include/fonts_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/utf-8.o encoding/utf-8.c

tmp_release/file.o: file/file.c include/file.h \
		include/debug_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/file.o file/file.c

tmp_release/ascii_font.o: fonts/ascii_font.c include/config.h \
		include/debug_manager.h \
		include/fonts_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/ascii_font.o fonts/ascii_font.c

tmp_release/fonts_manager.o: fonts/fonts_manager.c include/config.h \
		include/debug_manager.h \
		include/fonts_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/fonts_manager.o fonts/fonts_manager.c

tmp_release/freetype.o: fonts/freetype.c include/fonts_manager.h \
		include/config.h \
		include/debug_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/freetype.o fonts/freetype.c

tmp_release/gbk.o: fonts/gbk.c include/config.h \
		include/debug_manager.h \
		include/fonts_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/gbk.o fonts/gbk.c

tmp_release/input_manager.o: input/input_manager.c include/config.h \
		include/debug_manager.h \
		include/input_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/input_manager.o input/input_manager.c

tmp_release/stdin.o: input/stdin.c include/input_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/stdin.o input/stdin.c

tmp_release/touchscreen.o: input/touchscreen.c include/input_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/config.h \
		include/debug_manager.h \
		include/draw.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/touchscreen.o input/touchscreen.c

tmp_release/libjpeg.o: libjpeg/libjpeg.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/libjpeg.o libjpeg/libjpeg.c

tmp_release/main.o: main.c include/config.h \
		include/debug_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/encoding_manager.h \
		include/fonts_manager.h \
		include/picfmt_manager.h \
		include/render.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/main.o main.c

tmp_release/auto_page.o: page/auto_page.c include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/config.h \
		include/debug_manager.h \
		include/render.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/auto_page.o page/auto_page.c

tmp_release/browse_page.o: page/browse_page.c include/config.h \
		include/debug_manager.h \
		include/render.h \
		include/pic_operation.h \
		include/file.h \
		include/disp_manager.h \
		include/page_manager.h \
		include/input_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/browse_page.o page/browse_page.c

tmp_release/interval_page.o: page/interval_page.c include/config.h \
		include/debug_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/render.h \
		include/fonts_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/interval_page.o page/interval_page.c

tmp_release/main_page.o: page/main_page.c include/config.h \
		include/debug_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/render.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/main_page.o page/main_page.c

tmp_release/manual_page.o: page/manual_page.c include/config.h \
		include/debug_manager.h \
		include/render.h \
		include/pic_operation.h \
		include/file.h \
		include/disp_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/fonts_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/manual_page.o page/manual_page.c

tmp_release/page_manager.o: page/page_manager.c include/config.h \
		include/debug_manager.h \
		include/render.h \
		include/pic_operation.h \
		include/file.h \
		include/disp_manager.h \
		include/page_manager.h \
		include/input_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/page_manager.o page/page_manager.c

tmp_release/setting_page.o: page/setting_page.c include/config.h \
		include/debug_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/render.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/setting_page.o page/setting_page.c

tmp_release/bmp.o: render/format/bmp.c include/pic_operation.h \
		include/file.h \
		include/picfmt_manager.h \
		include/config.h \
		include/debug_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/bmp.o render/format/bmp.c

tmp_release/jpg.o: render/format/jpg.c include/config.h \
		include/debug_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/picfmt_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/jpg.o render/format/jpg.c

tmp_release/picfmt_manager.o: render/format/picfmt_manager.c include/config.h \
		include/debug_manager.h \
		include/pic_operation.h \
		include/file.h \
		include/picfmt_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/disp_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/picfmt_manager.o render/format/picfmt_manager.c

tmp_release/merge.o: render/operation/merge.c include/pic_operation.h \
		include/file.h \
		include/debug_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/merge.o render/operation/merge.c

tmp_release/zoom.o: render/operation/zoom.c include/pic_operation.h \
		include/file.h \
		include/debug_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/zoom.o render/operation/zoom.c

tmp_release/render.o: render/render.c include/config.h \
		include/debug_manager.h \
		include/render.h \
		include/pic_operation.h \
		include/file.h \
		include/disp_manager.h \
		include/page_manager.h \
		include/input_manager.h \
		include/fonts_manager.h \
		include/encoding_manager.h \
		include/picfmt_manager.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tmp_release/render.o render/render.c

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/book/PicturePro || mkdir -p $(INSTALL_ROOT)/book/PicturePro
	$(QINSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/book/PicturePro/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/book/PicturePro/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/book/PicturePro/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

